### ISSUE TITLE
Slices section example output is incorrect

### ISSUE THREAD

**Issue by samgiz** [ibokuri/zigbyexample#3]
It got me confused for a second, so I ran it locally and got the following output: 

```
~ zig run slices.zig 
len: 3
first: 2
elem: 2
elem: 3
elem: 4
len: 3
first: 2
elem: 2
elem: 3
elem: 4
```

Meaning the example output is incorrect and the two instances of `len: 2` should instead say `len: 3` in https://zig-by-example.com/slices.

**Comment by phan-do** [comment]
Thanks so much for finding this! It should be fixed now.
